// timesheet-service/src/main/resources/application.yml
server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/timesheetdb
    username: root
    password: rootpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: timesheet-service