# user-profile-service/src/main/resources/application.yml
spring:
  datasource:
    url: http://localhost:5432/userdb
    username: user_service
    password: grgjUHI9
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080


#or # Uncomment to use MySQL datasource
  # datasource:
  #   url: jdbc:mysql://localhost:3306/userdb
  #   username: root
  #   password: root
  #   driver-class-name: com.mysql.cj.jdbc.Driver
  # jpa:
  #   hibernate:
  #     ddl-auto: update
  #   show-sql: true
  #   properties:
  #     hibernate:
  #       dialect: org.hibernate.dialect.MySQL8Dialect
  # application:
  #   name: user-profile-service

---